### ISSUE TITLE
TODO September

### ISSUE THREAD

**Issue by nerik** [nerik/eu-trees4f-viz#1]
### Design
- [x] Layout: full scroll page?
- [x] Main/species nav
- [x] Timeseries
- [ ] Map timeseries UI
- [ ] Basemap
  - Some texture in sea?, less visible polys outline, dark green 
- [ ] Mobile

### Rendering/deck.gl
- [ ] Hexagons
- [ ] Hachures for "suitable"
- [ ] _Delayed points (https://github.com/pbeshai/deckgl-point-animation/blob/master/src/DelayedPointLayer.js)_
- [ ] _extruded_

### Global
- [x] Global layout
- [x] Styled components
- [x] i18n
  - [ ] translate
- [x] _URL nav_
  - [x] Move region state to GID
  - [ ] Map VP
- [ ] Scrollytelling intro
- [ ] Mobile UI
- [ ] Vector basemap
  - [ ] Maplibre + openmaptiles

### Features
- [ ] Species pages
  - [ ] Rich description with links and images
- [ ] Regions pages
  - [x] Species timeseries dropdowns 
    - [x] Reuse stats logic from species page
  - [x] _Overall species chart_
  - [ ] Highlight map cells belonging to region
    - [ ] _Lock graph?_
  - [x] Links from dropdowns in species page
    - [x] save bboxes in regions.json in order to fitBounds
- [ ] _Europe-wide Overall species chart ?_
- [ ] Hover tooltip region + hexagon
  - [x] Figure out deckgl multiple layers interaction
- [ ] _probability view_ 
- [ ] zoom on species bbox

### UI
- [x] Main nav
  - [x] Species menu
    - [x] Search species
    - [x] Sort species: Alphabetical latin, alphabetical french/english, by biome, by area
  - [x] Regions menu
    - ~search regions~
    - ~sort regions: Alphabetical, by country, by # of species~
  - [x] Language toggle
- [ ] Contextual/map
  - [x] Zoom buttons
  - [x] Sentence generator
  - [x] Years nav 
    - [ ] _Hover on types: tooltip + highlight on map_
    - [ ] _Tree longevity_
  - [ ] _RCP toggle_
  - [ ]  _Probability view toggle_ 
   
### Data
- [x] Species data/labels
- [ ] _RCP 4.5 tilesets_
- [x] Overall stats (total area by species by year, area lost/suitable by region by year) 
- [ ] _Species longevity_
- [ ] Collect links
  - https://forest.jrc.ec.europa.eu
  - wikipedia
  -  wikispecies
  -  EUFORGEN
  - Woodland trust?
  - GBIF https://www.gbif.org/species/5361865

### Bugfixes
- [x] timeseries dropdowns broken
- [ ] Map region selection
  - [ ] Figure out region/hexagon picking
- [x] Map regions fitBounds
- [x] Zero/very low data timeseries dropdowns
- [x] Paint map timeseries on first tileset load
- [x] Console errors on tile 404s
- [x] Crash with Cormus_domestica
- [ ] Locale not updating
- [ ] Region not zooming on page refresh
  properly use useResize?
- [x] activate scroll-behavior: smooth; only when intro is finished
- [ ] timesteps graph rendering to late in intro quercus ilex
- [ ] alpha order on regions nav
- [ ] missing region page title on countries
