### ISSUE TITLE
TODO March

### ISSUE THREAD

**Issue by nerik** [nerik/eu-trees4f-viz#22]
## Data

- [x] ~Experiment with PMtiles + MGL v2 (8)~
- [x] Generate tilesets (16)
    - [x] A tileset = one species 
        - [x] Point data with non-discrete value  + class + 4 timesteps + 2 RCPs
            - [x] { value_2035, cls_2035, … }
        - [x] Merged polygons with class 
            - [x] one geom per timestep per RCP
            - [x] { cls: … }
            - [ ] clip merged shape by coastlines
- [ ] Generate stats for RCP 4.5 (1)
- [ ] Longevity data (3)
- [ ] Collect links (Euforgen atlas links, GBIF, etc) (2)
- [x] Geodescriber (3) 🧪
- [ ] Region boundaries (3)
  - [x] simplified for detection on drag + locate me + generate geodescriber
  - [ ] complex + subtracted version in Mapbox Studio

## Design

- [ ] Home design
    - [ ] Link to scrollytelling intro
    - [ ] Link to stories
    - [ ] UI help
- [ ] Compare map?
- [ ] Expert mode/probability view?
- [ ] Locator button?
- [ ] Compare map button?
- [ ] three dots ... in region page's species list? 
- [ ] Refine waffle chart design
- [ ] New style layout CSS (8)
- [ ] New style UI CSS (4)
- [ ] CSS transitions (2)

## Map

- [ ] Set up MGL account (1) 🧪
- [ ] Icon style (2)
    - [ ] Generate textures
    - [ ] Apply style
- [ ] [deck.gl](http://deck.gl/) -> RMGL (8)
    - [ ] Set up basemap loading
    - [ ] Layer/source config to style
- [ ] Compare map (6)
- [ ] Select region while dragging logic (4)
    - [ ] Highlight region on map

## Species menu

- [ ] Create assets from Dall-E output (3)
- [ ] CSS layout (3)

## Species page

- [ ] Waffle chart (8)
    - [ ] Rendering logic
    - [ ] Hovers 
- [ ] CSS layout (2)

## Regions menu

- [ ] CSS Layout (2)
- [ ] Locate me button + logic (2)

## Regions page

- [ ] Static map (6)
    - [ ] Set up MGL style for static map
    - [ ] Apply style to isolate region
    - [ ] Apply bounds
- [ ] Bubble Chart (16) 🧪
  - [ ] Layout / transitions
  - [ ] Species list layout
  - [ ] Tooltips
  - [ ] Region-species modal
  
## Stories / intro

- [ ] Intro (16)
  - [ ] intro-specific logic
  - [ ] contents 
- [ ] Small multiples for several species (2)
- [ ] Story-version of UI components (year, RCP, compare) (3)

--- 
Est dev hours: 134
Lab hrs: 17
